"""
===========================================================
17_evaluate_stm32_fp32.py

Evaluate the predictions generated by the deployed
STM32 FP32 model.

Author : Dr. C Sivananda Reddy
===========================================================
"""

from pathlib import Path

import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)


# ==========================================================
# Project Paths
# ==========================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

Y_TEST_PATH = PROJECT_ROOT / "Deep_Learning" / "y_test.csv"

PREDICTION_PATH = (
    PROJECT_ROOT
    / "Deep_Learning"
    / "stm32_predictions.csv"
)


# ==========================================================
# Load Ground Truth
# ==========================================================

y_test = pd.read_csv(Y_TEST_PATH)

# Convert to 1-D array
y_true = y_test.iloc[:, 0]


# ==========================================================
# Load STM32 Predictions
# ==========================================================

prediction_df = pd.read_csv(PREDICTION_PATH)

y_pred = prediction_df.iloc[:, 0]


# ==========================================================
# Remove Invalid Predictions (if any)
# ==========================================================

valid_mask = y_pred >= 0

y_true = y_true[valid_mask]
y_pred = y_pred[valid_mask]


# ==========================================================
# Compute Metrics
# ==========================================================

accuracy = accuracy_score(
    y_true,
    y_pred,
)

precision = precision_score(
    y_true,
    y_pred,
    average="weighted",
)

recall = recall_score(
    y_true,
    y_pred,
    average="weighted",
)

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted",
)

cm = confusion_matrix(
    y_true,
    y_pred,
)

report = classification_report(
    y_true,
    y_pred,
    digits=4,
)


# ==========================================================
# Display Results
# ==========================================================

print("=" * 60)
print("STM32 FP32 Model Evaluation")
print("=" * 60)

print(f"Test Samples        : {len(y_true)}")

print(f"Accuracy            : {accuracy:.4f}")

print(f"Precision (Weighted): {precision:.4f}")

print(f"Recall (Weighted)   : {recall:.4f}")

print(f"F1-Score (Weighted) : {f1:.4f}")

print("\nConfusion Matrix")

print(cm)

print("\nClassification Report")

print(report)

print("=" * 60)